CREATE DATABASE  quanlytrungtam;
USE quanlytrungtam;

CREATE TABLE VAITRO (
    maVaiTro INT AUTO_INCREMENT PRIMARY KEY,
    tenVaiTro VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE NGUOIDUNG (
    maND INT AUTO_INCREMENT PRIMARY KEY,
    tenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL,
    maVaiTro INT NOT NULL,
    FOREIGN KEY (maVaiTro) REFERENCES VAITRO(maVaiTro)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE HOCVIEN (
    maND INT PRIMARY KEY,
    hoTen VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    SDT VARCHAR(10) NOT NULL UNIQUE,
    diaChi VARCHAR(200),
    FOREIGN KEY (maND) REFERENCES NGUOIDUNG(maND)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TRUNGTAM (
    maTT INT AUTO_INCREMENT PRIMARY KEY,
    tenTT VARCHAR(200) NOT NULL,
    diaChiTT VARCHAR(255) NOT NULL,
    SDT VARCHAR(10)
);

CREATE TABLE KHOAHOC (
    maKH INT AUTO_INCREMENT PRIMARY KEY,
    tenKH VARCHAR(200) NOT NULL,
    moTa VARCHAR(255),
    hocPhi DECIMAL(18,2) NOT NULL,
    hinhAnh VARCHAR(255)
);

CREATE TABLE LOPHOC (
    maLH INT AUTO_INCREMENT PRIMARY KEY,
    maKH INT NOT NULL,
    maTT INT NOT NULL,
    tenLH VARCHAR(100) NOT NULL,
    siSoMax INT DEFAULT 30,
    ngayKhaiGiang DATE,
    FOREIGN KEY (maKH) REFERENCES KHOAHOC(maKH),
    FOREIGN KEY (maTT) REFERENCES TRUNGTAM(maTT)
);

CREATE TABLE PHIEUDANGKY (
    maDK INT AUTO_INCREMENT PRIMARY KEY,
    maND INT NOT NULL,
    maLH INT NOT NULL,
    ngayLap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trangThaiTT ENUM('ChuaThanhToan', 'DaThanhToan') DEFAULT 'ChuaThanhToan',
    tinhTrangDuyet ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    UNIQUE (maND, maLH),
    FOREIGN KEY (maND) REFERENCES NGUOIDUNG(maND),
    FOREIGN KEY (maLH) REFERENCES LOPHOC(maLH)
);

CREATE INDEX idx_user_username ON NGUOIDUNG(tenDangNhap);
CREATE INDEX idx_lophoc_makh ON LOPHOC(maKH);
CREATE INDEX idx_phieu_mand ON PHIEUDANGKY(maND);

CREATE OR REPLACE VIEW View_ChiTietLopHoc AS
SELECT l.maLH, l.tenLH, l.siSoMax, l.ngayKhaiGiang, k.tenKH, t.tenTT
FROM LOPHOC l
JOIN KHOAHOC k ON l.maKH = k.maKH
JOIN TRUNGTAM t ON l.maTT = t.maTT;
ALTER TABLE PHIEUDANGKY
    ADD hoTen VARCHAR(100),
ADD email VARCHAR(100),
ADD SDT VARCHAR(10),
ADD diaChi VARCHAR(200);